services:
  db:
    image: postgres:15
    container_name: finanzen_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: finanzen
    ports:
      - "5432:5432"
    volumes:
      - finanzen_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  finanzen_db_data:
